function contentsCallback(this, varargin)
%CONTENTSCALLBACK Help contents callback function.
%
% Copyright 2013-2014 Mikhail S. Jones

    % Create dialog box
    helpdlg({'Spacebar toggles play/pause', ...
        'Up/down arrows increase/decrease playback speed', ...
        'Left/right arrows goto next/previous frame', ...
        ''}, ...
        'Help');
end % contentsCallback
